#!/bin/bash
S=/root/daisy-build/kernel_source
echo "==P1 perf/gaming in base?=="
grep -n "PERFORMANCE" "$S/arch/arm64/configs/daisy_defconfig"
grep -n "PERFORMANCE" "$S/drivers/cpufreq/Kconfig"
echo "(empty above = no PERFORMANCE symbol)"
echo ""
echo "==P2 boost Kconfig defaults=="
sed -n '267,300p' "$S/drivers/devfreq/Kconfig"
echo ""
echo "==P3 boost freqs in base=="
grep -n "INPUT_BOOST\|MAX_BOOST\|BASE_BOOST\|WAKE_BOOST\|DEVFREQ.*BOOST" "$S/arch/arm64/configs/daisy_defconfig"
echo ""
echo "==P4 IO in base=="
grep -n "BFQ\|IOSCHED\|ZRAM" "$S/arch/arm64/configs/daisy_defconfig"
