#!/bin/bash
S=/root/daisy-build/kernel_source
C="$S/out/.config"
echo "=== FolkPatch/KernelPatch needs vs v2.3 .config ==="
echo "--- 1. KALLSYMS (finds syscall table) ---"
grep -E "^CONFIG_KALLSYMS|CONFIG_KALLSYMS_ALL" "$C"
echo "--- 2. KPROBES (hook engine) ---"
grep -E "^CONFIG_KPROBES|CONFIG_KRETPROBES|CONFIG_HAVE_KPROBES" "$C"
echo "--- 3. STRIP_ASM_SYMS must be OFF ---"
grep -E "STRIP_ASM_SYMS" "$C" || echo "not present (good)"
echo "--- 4. OVERLAYFS (module mount) ---"
grep -E "^CONFIG_OVERLAY_FS" "$C"
echo "--- 5. KALLSYMS in /proc (kptr_restrict) ---"
grep -E "KPTR_RESTRICT" "$C"
echo "--- 6. LSM / SELinux hooks ---"
grep -E "^CONFIG_SECURITY_SELINUX=|^CONFIG_LSM=" "$C"
echo "--- 7. Module loading ---"
grep -E "^CONFIG_MODULES=|^CONFIG_KPROBES_ON_FTRACE" "$C"
echo "--- 8. version ---"
grep -E "^VERSION|^PATCHLEVEL|^SUBLEVEL" "$S/Makefile"
grep -E "CONFIG_LOCALVERSION=" "$C"
echo "--- 9. DEBUG_INFO needed? ---"
grep -E "^CONFIG_DEBUG_INFO" "$C" || echo "DEBUG_INFO off (ok for KP)"
